# Little helper

In [11]:
def to_um(value_str):
    units = {
        'nm': 1e-3,   # nanometers to micrometers
        'um': 1,      # micrometers to micrometers
        'mm': 1e3,    # millimeters to micrometers
        'cm': 1e4,    # centimeters to micrometers
        'm':  1e6     # meters to micrometers
    }
    
    # Clean and split the input
    parts = value_str.strip().lower().split()
    if len(parts) != 2:
        raise ValueError("Input must be in the form '<number> <unit>'")

    number, unit = parts
    if unit not in units:
        raise ValueError(f"Unsupported unit: {unit}")
    
    return float(number) * units[unit]

# General import

In [12]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [13]:
import qiskit_metal as metal
from qiskit_metal import designs, draw
from qiskit_metal import MetalGUI, Dict, open_docs

%metal_heading Genshin Impact!

# Layout

In [14]:
from qiskit_metal.qlibrary.qubits.transmon_pocket_6 import TransmonPocket6
from qiskit_metal.qlibrary.qubits.transmon_cross import TransmonCross
from qiskit_metal.qlibrary.qubits.transmon_cross_fl import TransmonCrossFL

from qiskit_metal.qlibrary.couplers.tunable_coupler_01 import TunableCoupler01

from qiskit_metal.qlibrary.tlines.meandered import RouteMeander
from qiskit_metal.qlibrary.tlines.pathfinder import RoutePathfinder
from qiskit_metal.qlibrary.tlines.anchored_path import RouteAnchors
from qiskit_metal.qlibrary.tlines.straight_path import RouteStraight

from qiskit_metal.qlibrary.lumped.cap_n_interdigital import CapNInterdigital
from qiskit_metal.qlibrary.couplers.cap_n_interdigital_tee import CapNInterdigitalTee
from qiskit_metal.qlibrary.couplers.coupled_line_tee import CoupledLineTee

from qiskit_metal.qlibrary.terminations.launchpad_wb import LaunchpadWirebond
from qiskit_metal.qlibrary.terminations.launchpad_wb_coupled import LaunchpadWirebondCoupled
from qiskit_metal.qlibrary.terminations.launchpad_wb_driven import LaunchpadWirebondDriven
from qiskit_metal.qlibrary.terminations.open_to_ground import OpenToGround
from qiskit_metal.qlibrary.terminations.short_to_ground import ShortToGround

from qiskit_metal.qlibrary.qubits.JJ_Manhattan import jj_manhattan

In [15]:
design = metal.designs.DesignPlanar()

gui = metal.MetalGUI(design)

In [16]:
design.overwrite_enabled = True
design.chips.main

{'material': 'silicon',
 'layer_start': '0',
 'layer_end': '2048',
 'size': {'center_x': '0.0mm',
  'center_y': '0.0mm',
  'center_z': '0.0mm',
  'size_x': '9mm',
  'size_y': '6mm',
  'size_z': '-750um',
  'sample_holder_top': '890um',
  'sample_holder_bottom': '1650um'}}

In [17]:
design._chips['main']['size']['size_x'] = '5mm'
design._chips['main']['size']['size_y'] = '5mm'
design.variables['cpw_width'] = '10 um'
design.variables['cpw_gap'] = '6 um'

## The Qubits

In [18]:
TransmonCross.get_template_options(design)

{'pos_x': '0.0um',
 'pos_y': '0.0um',
 'orientation': '0.0',
 'chip': 'main',
 'layer': '1',
 'connection_pads': {},
 '_default_connection_pads': {'connector_type': '0',
  'claw_length': '30um',
  'ground_spacing': '5um',
  'claw_width': '10um',
  'claw_gap': '6um',
  'connector_location': '0'},
 'cross_width': '20um',
 'cross_length': '200um',
 'cross_gap': '20um',
 'hfss_inductance': '10nH',
 'hfss_capacitance': 0,
 'hfss_resistance': 0,
 'hfss_mesh_kw_jj': 7e-06,
 'q3d_inductance': '10nH',
 'q3d_capacitance': 0,
 'q3d_resistance': 0,
 'q3d_mesh_kw_jj': 7e-06,
 'gds_cell_name': 'my_other_junction'}

In [19]:
jj_manhattan.get_template_options(design)

{'pos_x': '0.0um',
 'pos_y': '0.0um',
 'orientation': '0.0',
 'chip': 'main',
 'layer': '1',
 'JJ_pad_lower_width': '25um',
 'JJ_pad_lower_height': '10um',
 'JJ_pad_lower_pos_x': '0',
 'JJ_pad_lower_pos_y': '0',
 'finger_lower_width': '1um',
 'finger_lower_height': '20um',
 'extension': '1um'}

### Qubit 1

In [20]:
xmon_options = dict(
    pos_x = '1.0mm',
    pos_y = '4.25mm',
    orientation = '270',
    cross_width = '24um',
    cross_length = '160um',
    cross_gap = '24um',
    connection_pads=dict(
        connector_1 = dict(connector_location = '90', connector_type = '0', claw_length='90um')
    ),
)

Qubit_1 = TransmonCross(design, 'Qubit_1', options=xmon_options)

gui.rebuild()
gui.autoscale()
# gui.zoom_on_components(['Qubit_1'])

### Qubit 2

In [21]:
xmon_options = dict(
    pos_x = '4.0mm',
    pos_y = '3.55mm',
    orientation = '90',
    cross_width = '24um',
    cross_length = '160um',
    cross_gap = '24um',
    connection_pads=dict(
        connector_1 = dict(connector_location = '90', connector_type = '0', claw_length='90um')
    ),
)

Qubit_2 = TransmonCross(design, 'Qubit_2', options=xmon_options)


gui.rebuild()
gui.autoscale()
gui.zoom_on_components(['Qubit_2'])

### Qubit 3

In [22]:
xmon_options = dict(
    pos_x = '1.0mm',
    pos_y = '2.85mm',
    orientation = '270',
    cross_width = '24um',
    cross_length = '160um',
    cross_gap = '24um',
    connection_pads=dict(
        connector_1 = dict(connector_location = '90', connector_type = '0', claw_length='90um')
    ),
)

Qubit_3 = TransmonCross(design, 'Qubit_3', options=xmon_options)
gui.rebuild()
gui.autoscale()
gui.zoom_on_components(['Qubit_3'])

### Qubit 4

In [23]:
xmon_options = dict(
    pos_x = '4.0mm',
    pos_y = '2.15mm',
    orientation = '90',
    cross_width = '24um',
    cross_length = '160um',
    cross_gap = '24um',
    connection_pads=dict(
        connector_1 = dict(connector_location = '90', connector_type = '0', claw_length='90um')
    ),
)

Qubit_4 = TransmonCross(design, 'Qubit_4', options=xmon_options)
gui.rebuild()
gui.autoscale()
gui.zoom_on_components(['Qubit_4'])

### Qubit 5

In [24]:
xmon_options = dict(
    pos_x = '1.0mm',
    pos_y = '1.45mm',
    orientation = '270',
    cross_width = '24um',
    cross_length = '160um',
    cross_gap = '24um',
    connection_pads=dict(
        connector_1 = dict(connector_location = '90', connector_type = '0', claw_length='90um')
    ),
)

Qubit_5 = TransmonCross(design, 'Qubit_5', options=xmon_options)
gui.rebuild()
gui.autoscale()
gui.zoom_on_components(['Qubit_5'])

### Qubit 6

In [25]:
xmon_options = dict(
    pos_x = '4.0mm',
    pos_y = '0.75mm',
    orientation = '90',
    cross_width = '24um',
    cross_length = '160um',
    cross_gap = '24um',
    connection_pads=dict(
        connector_1 = dict(connector_location = '90', connector_type = '0', claw_length='90um')
    ),
)

Qubit_6 = TransmonCross(design, 'Qubit_6', options=xmon_options)
gui.rebuild()
gui.autoscale()
gui.zoom_on_components(['Qubit_6'])

In [26]:
LaunchpadWirebond.default_options

{'trace_width': 'cpw_width',
 'trace_gap': 'cpw_gap',
 'lead_length': '25um',
 'pad_width': '80um',
 'pad_height': '80um',
 'pad_gap': '58um',
 'taper_height': '122um'}

# Readout line

### Readout launchpad

In [27]:
output = LaunchpadWirebondDriven(design, 'output', options = dict(pos_x='2500um', pos_y='260um', orientation='90', lead_length='30um'))  # something about a drive function
input = LaunchpadWirebondDriven(design, 'input', options = dict(pos_x='2500um', pos_y='4740um', orientation='270', lead_length='30um'))
gui.rebuild()
gui.autoscale()

### Readout bus

In [28]:
IObus = RouteStraight(design,'IObus',options=Dict(
    pin_inputs=Dict(
        start_pin=Dict(
            component = 'input',
            pin = 'tie'
        ),
        end_pin=Dict(
            component = 'output',
            pin = 'tie'
        )
    )
))
gui.rebuild()
# gui.autoscale()

# Resonator

In [29]:
# the unit is um in this box

pos_ro_x = 2500
cpw_width = 10
epsilon = 11.4
fillet='99.99um'
cpw_options = Dict(
    hfss_wire_bonds = True,
    lead=Dict(
        start_straight='100um',
        # end_straight='250um'
    ),
    fillet=fillet,
    meander=Dict(spacing="200um")
)


def pos_from_offset(offset):
    return pos_ro_x + offset

def quarter_wave_length(frequency_ghz, epsilon_eff):
    """input in GHz, output in um"""
    c = 3e8
    frequency_hz = frequency_ghz * 1e9
    wavelength = c / (frequency_hz * (epsilon_eff ** 0.5))
    quarter_wavelength = wavelength / 4
    return quarter_wavelength * 1e6

def generate_readout_frequencies(center_freq_ghz=7.4, spacing_mhz=30, num_qubits=6):
    start_freq = center_freq_ghz - (spacing_mhz * (num_qubits - 1) / 2) / 1000
    return [round(start_freq + i * spacing_mhz / 1000, 6) for i in range(num_qubits)]

def connect(cpw_name: str, pin1_comp_name: str, pin1_comp_pin: str, pin2_comp_name: str, pin2_comp_pin: str,
            length: str, asymmetry='0 um'):
    """Connect two pins with a CPW."""
    myoptions = Dict(
        total_length=length,
        pin_inputs=Dict(
            start_pin=Dict(component=pin1_comp_name,pin=pin1_comp_pin),
            end_pin=Dict(component=pin2_comp_name,pin=pin2_comp_pin),
            ),
        )
    myoptions.update(cpw_options)
    myoptions.meander.asymmetry = asymmetry
    return RouteMeander(design, cpw_name, myoptions)

frequencies = generate_readout_frequencies()

length_um_list = [quarter_wave_length(freq, epsilon) for freq in frequencies]

# length_um = quarter_wave_length(7.4, 6.3)
# for length_um in length_um_list:
#     print(f"{length_um:.2f}")

In [30]:
ShortToGround.get_template_options(design)

{'pos_x': '0.0um',
 'pos_y': '0.0um',
 'orientation': '0.0',
 'chip': 'main',
 'layer': '1',
 'width': '10um'}

### Readout Resonator for Qubit 1

In [31]:
offset_ro_x_1 = -25
pos_x_cp1 = pos_from_offset(offset_ro_x_1)
pos_y_cp1 = 4250

# coupling_pin_1 = OpenToGround(design, 'coupling_pin_1', options=dict(
#     pos_x = f"{pos_x_cp1}um",
#     pos_y = f"{pos_y_cp1}um",
#     orientation = "270.0"
# ))

coupling_pin_1 = ShortToGround(design, 'coupling_pin_1', options=dict(
    pos_x = f"{pos_x_cp1}um",
    pos_y = f"{pos_y_cp1}um",
    orientation = "270.0"
))

asym = 0
cpw1 = connect('cpw1', 'Qubit_1', 'connector_1', 'coupling_pin_1', 'short', '4037um', f'+{asym}um')

gui.rebuild()
# gui.autoscale()

In [32]:
offset_ro_x_2 = +40
pos_x_cp2 = pos_from_offset(offset_ro_x_2)
pos_y_cp2 = 3550

coupling_pin_2 = OpenToGround(design, 'coupling_pin_2', options=dict(
    pos_x = f"{pos_x_cp2}um",
    pos_y = f"{pos_y_cp2}um",
    orientation = "90.0"
))

asym = 0
cpw2 = connect('cpw2', 'Qubit_2', 'connector_1', 'coupling_pin_2', 'open', f"{length_um_list[1]}um", f'+{asym}um')

gui.rebuild()
gui.autoscale()

In [33]:
offset_ro_x_3 = -40
pos_x_cp3 = pos_from_offset(offset_ro_x_3)
pos_y_cp3 = 2850

coupling_pin_3 = OpenToGround(design, 'coupling_pin_3', options=dict(
    pos_x = f"{pos_x_cp3}um",
    pos_y = f"{pos_y_cp3}um",
    orientation = "270.0"
))

asym = 0
cpw3 = connect('cpw3', 'Qubit_3', 'connector_1', 'coupling_pin_3', 'open', f"{length_um_list[2]}um", f'+{asym}um')

gui.rebuild()
gui.autoscale()

In [34]:
offset_ro_x_4 = +40
pos_x_cp4 = pos_from_offset(offset_ro_x_4)
pos_y_cp4 = 2150

coupling_pin_4 = OpenToGround(design, 'coupling_pin_4', options=dict(
    pos_x = f"{pos_x_cp4}um",
    pos_y = f"{pos_y_cp4}um",
    orientation = "90.0"
))

asym = 0
cpw4 = connect('cpw4', 'Qubit_4', 'connector_1', 'coupling_pin_4', 'open', f"{length_um_list[3]}um", f'+{asym}um')

gui.rebuild()
gui.autoscale()

In [35]:
offset_ro_x_5 = -40
pos_x_cp5 = pos_from_offset(offset_ro_x_5)
pos_y_cp5 = 1450

coupling_pin_5 = OpenToGround(design, 'coupling_pin_5', options=dict(
    pos_x = f"{pos_x_cp5}um",
    pos_y = f"{pos_y_cp5}um",
    orientation = "270.0"
))

asym = 0
cpw5 = connect('cpw5', 'Qubit_5', 'connector_1', 'coupling_pin_5', 'open', f"{length_um_list[4]}um", f'+{asym}um')

gui.rebuild()
gui.autoscale()

In [36]:
offset_ro_x_6 = +40
pos_x_cp6 = pos_from_offset(offset_ro_x_6)
pos_y_cp6 = 750

coupling_pin_6 = OpenToGround(design, 'coupling_pin_6', options=dict(
    pos_x = f"{pos_x_cp6}um",
    pos_y = f"{pos_y_cp6}um",
    orientation = "90.0"
))

asym = 0
cpw6 = connect('cpw6', 'Qubit_6', 'connector_1', 'coupling_pin_6', 'open', f"{length_um_list[5]}um", f'+{asym}um')

gui.rebuild()
gui.autoscale()

# Analysis

In [27]:
from qiskit_metal.analyses.quantization import EPRanalysis
eig_qb = EPRanalysis(design, "hfss")

In [28]:
hfss = eig_qb.sim.renderer

In [29]:
hfss.start()

INFO 02:28PM [connect_project]: Connecting to Ansys Desktop API...
INFO 02:28PM [load_ansys_project]: 	Opened Ansys App
INFO 02:28PM [load_ansys_project]: 	Opened Ansys Desktop v2024.1.0
INFO 02:28PM [load_ansys_project]: 	Opened Ansys Project
	Folder:    C:/Users/24716/Documents/Ansoft/
	Project:   Project7
INFO 02:28PM [connect_design]: No active design found (or error getting active design).
INFO 02:28PM [connect]: 	 Connected to project "Project7". No design detected

True

In [31]:
hfss.activate_ansys_design("Transmon_cpw", "eigenmode")

02:29PM 18s WARNING [activate_ansys_design]: The design_name=Transmon_cpw was not in active project.  Designs in active project are:
[].  A new design will be added to the project.

com_error: (-2147352567, '发生意外。', (0, None, None, None, 0, -2147024367), None)

In [ ]:
# hfss.render_design(['Qubit_1','cpw1'],[])

In [ ]:
eig_qb.sim.setup.name = 'Tune_Qubit_1'
eig_qb.sim.setup.freq_ghz = 4
eig_qb.sim.setup.min_freq_ghz = 3
eig_qb.sim.setup.max_passes = 12
eig_qb.sim.setup.max_delta_f = 0.1
eig_qb.sim.setup.n_modes = 3
eig_qb.sim.setup

{'name': 'Tune_Qubit_1',
 'reuse_selected_design': True,
 'reuse_setup': True,
 'min_freq_ghz': 3,
 'n_modes': 3,
 'max_delta_f': 0.1,
 'max_passes': 12,
 'min_passes': 1,
 'min_converged': 1,
 'pct_refinement': 30,
 'basis_order': 1,
 'vars': {'Lj': '10 nH', 'Cj': '0 fF'},
 'freq_ghz': 4,
 'run': {'name': 'Qubit_1',
  'components': ['Qubit_1', 'cpw1'],
  'open_terminations': [],
  'port_list': None,
  'jj_to_port': None,
  'ignored_jjs': None,
  'box_plus_buffer': True}}

## below is something from the past

In [ ]:
# Qubit_1.options.hfss_inductance = '15nH'

In [ ]:
del eig_qb.setup.junctions['jj']
eig_qb.setup.junctions.jj = Dict(rect='JJ_rect_Lj_Qubit_1_rect_jj', line='JJ_Lj_Qubit_1_rect_jj_',
                                 Lj_variable = 'Lj', Cj_variable = 'Cj')
eig_qb.setup.sweep_variable = 'Lj'
eig_qb.setup

{'junctions': {'jj': {'rect': 'JJ_rect_Lj_Qubit_1_rect_jj',
   'line': 'JJ_Lj_Qubit_1_rect_jj_',
   'Lj_variable': 'Lj',
   'Cj_variable': 'Cj'}},
 'dissipatives': {'dielectrics_bulk': ['main']},
 'cos_trunc': 8,
 'fock_trunc': 7,
 'sweep_variable': 'Lj'}

In [ ]:
eig_qb.sim.run(name="Qubit_1", components=['Qubit_1', 'cpw1'], open_terminations=[])

INFO 02:08PM [connect_project]: Connecting to Ansys Desktop API...
INFO 02:08PM [load_ansys_project]: 	Opened Ansys App
INFO 02:08PM [load_ansys_project]: 	Opened Ansys Desktop v2025.1.0
INFO 02:08PM [load_ansys_project]: 	Opened Ansys Project
	Folder:    C:/Users/91566/Documents/Ansoft/
	Project:   Project33
INFO 02:08PM [connect_design]: 	Opened active design
	Design:    Qubit_1_hfss [Solution type: Eigenmode]
INFO 02:08PM [get_setup]: 	Opened setup `Setup`  (<class 'pyEPR.ansys.HfssEMSetup'>)
INFO 02:08PM [connect]: 	Connected to project "Project33" and design "Qubit_1_hfss" 😀

INFO 02:08PM [connect_design]: 	Opened active design
	Design:    Qubit_1_hfss [Solution type: Eigenmode]

com_error: (-2147417851, 'The server threw an exception.', None, None)

In [ ]:
eig_qb.sim.plot_convergences()

In [ ]:
eig_qb.run_epr()

Design "Qubit_1_hfss" info:
	# eigenmodes    2
	# variations    1
Design "Qubit_1_hfss" info:
	# eigenmodes    2
	# variations    1

        energy_elec_all       = 2.14637700267949e-24
        energy_elec_substrate = 1.97164390718289e-24
        EPR of substrate = 91.9%

        energy_mag    = 2.1463334895109e-24
        energy_mag % of energy_elec_all  = 100.0%


Variation 0  [1/1]

  Mode 0 at 6.80 GHz   [1/2]
    Calculating ℰ_magnetic,ℰ_electric
       (ℰ_E-ℰ_H)/ℰ_E       ℰ_E       ℰ_H
                0.0%  1.073e-24 1.073e-24

    Calculating junction energy participation ration (EPR)
	method=`line_voltage`. First estimates:
	junction        EPR p_0j   sign s_0j    (p_capacitive)
		Energy fraction (Lj over Lj&Cj)= 96.47%
	jj              2.02651e-05  (+)        7.40852e-07
		(U_tot_cap-U_tot_ind)/mean=0.00%
Calculating Qdielectric_main for mode 0 (0/1)
p_dielectric_main_0 = 0.9185916102909847

  Mode 1 at 20.42 GHz   [2/2]
    Calculating ℰ_magnetic,ℰ_electric
       (ℰ_E-ℰ_H)/ℰ_E       ℰ_E       ℰ_H
                0.0%  1.113e-24 1.113e-24

    Calculating junction energy participation ration (EPR)
	method=`line_voltage`. First estimates:
	junction        EPR p_1j   sign s_1j    (p_capacitive)
		Energy fraction (Lj over Lj&Cj)= 75.24%
	jj              1.56854e-06  (+)        5.16278e-07
		(U_tot_cap-U_tot_ind)/mean=0.00%
Calculating Qdielectric_main for mode 1 (1/1)
p_dielectric_main_1 = 0.9166536958814117

WARNING 02:06PM [__init__]: <p>Error: <class 'IndexError'></p>

ANALYSIS DONE. Data saved to:

C:\data-pyEPR\Project33\Qubit_1_hfss\2025-07-28 14-06-24.npz


	 Differences in variations:



 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
Variation 0

Starting the diagonalization
Finished the diagonalization
sdag: Quantum object: dims=[[1, 1], [7, 7]], shape=(1, 49), type='bra', dtype=Dense
Qobj data =
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]]
sdag: Quantum object: dims=[[1, 1], [7, 7]], shape=(1, 49), type='bra', dtype=Dense
Qobj data =
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]]
sdag: Quantum object: dims=[[1, 1], [7, 7]], shape=(1, 49), type='bra', dtype=Dense
Qobj data =
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]]
sdag: Quantum object: dims=[[1, 1], [7, 7]], shape=(1, 49), type='bra', dtype=Dense
Qobj data =
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]]
sdag: Quantum object: dims=[[1, 1], [7, 7]], shape=(1, 49), type='bra', dtype=Dense
Qobj data =
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]]
sdag: Quantum object: dims=[[1, 1], [7, 7]], shape=(1, 49), type='bra', dtype=Dense
Qobj data =
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]]
sdag: Quantum object: dims=[[1, 1], [7, 7]], shape=(1, 49), type='bra', dtype=Dense
Qobj data =
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]]
sdag: Quantum object: dims=[[1, 1], [7, 7]], shape=(1, 49), type='bra', dtype=Dense
Qobj data =
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]]
sdag: Quantum object: dims=[[1, 1], [7, 7]], shape=(1, 49), type='bra', dtype=Dense
Qobj data =
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]]
sdag: Quantum object: dims=[[1, 1], [7, 7]], shape=(1, 49), type='bra', dtype=Dense
Qobj data =
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]]
sdag: Quantum object: dims=[[1, 1], [7, 7]], shape=(1, 49), type='bra', dtype=Dense
Qobj data =
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]]
sdag: Quantum object: dims=[[1, 1], [7, 7]], shape=(1, 49), type='bra', dtype=Dense
Qobj data =
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]]
sdag: Quantum object: dims=[[1, 1], [7, 7]], shape=(1, 49), type='bra', dtype=Dense
Qobj data =
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]]
sdag: Quantum object: dims=[[1, 1], [7, 7]], shape=(1, 49), type='bra', dtype=Dense
Qobj data =
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]]
sdag: Quantum object: dims=[[1, 1], [7, 7]], shape=(1, 49), type='bra', dtype=Dense
Qobj data =
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]]
sdag: Quantum object: dims=[[1, 1], [7, 7]], shape=(1, 49), type='bra', dtype=Dense
Qobj data =
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]]
sdag: Quantum object: dims=[[1, 1], [7, 7]], shape=(1, 49), type='bra', dtype=Dense
Qobj data =
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]]
sdag: Quantum object: dims=[[1, 1], [7, 7]], shape=(1, 49), type='bra', dtype=Dense
Qobj data =
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]]
sdag: Quantum object: dims=[[1, 1], [7, 7]], shape=(1, 49), type='bra', dtype=Dense
Qobj data =
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]]
sdag: Quantum object: dims=[[1, 1], [7, 7]], shape=(1, 49), type='bra', dtype=Dense
Qobj data =
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]]
sdag: Quantum object: dims=[[1, 1], [7, 7]], shape=(1, 49), type='bra', dtype=Dense
Qobj data =
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]]
sdag: Quantum object: dims=[[1, 1], [7, 7]], shape=(1, 49), type='bra', dtype=Dense
Qobj data =
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]]
sdag: Quantum object: dims=[[1, 1], [7, 7]], shape=(1, 49), type='bra', dtype=Dense
Qobj data =
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]]
sdag: Quantum object: dims=[[1, 1], [7, 7]], shape=(1, 49), type='bra', dtype=Dense
Qobj data =
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]]
sdag: Quantum object: dims=[[1, 1], [7, 7]], shape=(1, 49), type='bra', dtype=Dense
Qobj data =
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]]
sdag: Quantum object: dims=[[1, 1], [7, 7]], shape=(1, 49), type='bra', dtype=Dense
Qobj data =
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]]
sdag: Quantum object: dims=[[1, 1], [7, 7]], shape=(1, 49), type='bra', dtype=Dense
Qobj data =
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]]
sdag: Quantum object: dims=[[1, 1], [7, 7]], shape=(1, 49), type='bra', dtype=Dense
Qobj data =
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]]
sdag: Quantum object: dims=[[1, 1], [7, 7]], shape=(1, 49), type='bra', dtype=Dense
Qobj data =
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]]
sdag: Quantum object: dims=[[1, 1], [7, 7]], shape=(1, 49), type='bra', dtype=Dense
Qobj data =
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]]
sdag: Quantum object: dims=[[1, 1], [7, 7]], shape=(1, 49), type='bra', dtype=Dense
Qobj data =
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]]
sdag: Quantum object: dims=[[1, 1], [7, 7]], shape=(1, 49), type='bra', dtype=Dense
Qobj data =
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]]
sdag: Quantum object: dims=[[1, 1], [7, 7]], shape=(1, 49), type='bra', dtype=Dense
Qobj data =
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]]
sdag: Quantum object: dims=[[1, 1], [7, 7]], shape=(1, 49), type='bra', dtype=Dense
Qobj data =
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]]
sdag: Quantum object: dims=[[1, 1], [7, 7]], shape=(1, 49), type='bra', dtype=Dense
Qobj data =
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]]
sdag: Quantum object: dims=[[1, 1], [7, 7]], shape=(1, 49), type='bra', dtype=Dense
Qobj data =
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]]
sdag: Quantum object: dims=[[1, 1], [7, 7]], shape=(1, 49), type='bra', dtype=Dense
Qobj data =
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]]
sdag: Quantum object: dims=[[1, 1], [7, 7]], shape=(1, 49), type='bra', dtype=Dense
Qobj data =
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]]
sdag: Quantum object: dims=[[1, 1], [7, 7]], shape=(1, 49), type='bra', dtype=Dense
Qobj data =
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]]
sdag: Quantum object: dims=[[1, 1], [7, 7]], shape=(1, 49), type='bra', dtype=Dense
Qobj data =
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]]
sdag: Quantum object: dims=[[1, 1], [7, 7]], shape=(1, 49), type='bra', dtype=Dense
Qobj data =
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]]
sdag: Quantum object: dims=[[1, 1], [7, 7]], shape=(1, 49), type='bra', dtype=Dense
Qobj data =
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]]
sdag: Quantum object: dims=[[1, 1], [7, 7]], shape=(1, 49), type='bra', dtype=Dense
Qobj data =
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]]
sdag: Quantum object: dims=[[1, 1], [7, 7]], shape=(1, 49), type='bra', dtype=Dense
Qobj data =
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]]
sdag: Quantum object: dims=[[1, 1], [7, 7]], shape=(1, 49), type='bra', dtype=Dense
Qobj data =
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]]
sdag: Quantum object: dims=[[1, 1], [7, 7]], shape=(1, 49), type='bra', dtype=Dense
Qobj data =
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]]
sdag: Quantum object: dims=[[1, 1], [7, 7]], shape=(1, 49), type='bra', dtype=Dense
Qobj data =
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]]
sdag: Quantum object: dims=[[1, 1], [7, 7]], shape=(1, 49), type='bra', dtype=Dense
Qobj data =
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]]
sdag: Quantum object: dims=[[1, 1], [7, 7]], shape=(1, 49), type='bra', dtype=Dense
Qobj data =
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]]
sdag: Quantum object: dims=[[1, 1], [7, 7]], shape=(1, 49), type='bra', dtype=Dense
Qobj data =
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]]
sdag: Quantum object: dims=[[1, 1], [7, 7]], shape=(1, 49), type='bra', dtype=Dense
Qobj data =
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]]
sdag: Quantum object: dims=[[1, 1], [7, 7]], shape=(1, 49), type='bra', dtype=Dense
Qobj data =
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]]
sdag: Quantum object: dims=[[1, 1], [7, 7]], shape=(1, 49), type='bra', dtype=Dense
Qobj data =
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]]
sdag: Quantum object: dims=[[1, 1], [7, 7]], shape=(1, 49), type='bra', dtype=Dense
Qobj data =
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]]
sdag: Quantum object: dims=[[1, 1], [7, 7]], shape=(1, 49), type='bra', dtype=Dense
Qobj data =
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]]
sdag: Quantum object: dims=[[1, 1], [7, 7]], shape=(1, 49), type='bra', dtype=Dense
Qobj data =
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]]
sdag: Quantum object: dims=[[1, 1], [7, 7]], shape=(1, 49), type='bra', dtype=Dense
Qobj data =
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]]
sdag: Quantum object: dims=[[1, 1], [7, 7]], shape=(1, 49), type='bra', dtype=Dense
Qobj data =
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]]
sdag: Quantum object: dims=[[1, 1], [7, 7]], shape=(1, 49), type='bra', dtype=Dense
Qobj data =
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]]
sdag: Quantum object: dims=[[1, 1], [7, 7]], shape=(1, 49), type='bra', dtype=Dense
Qobj data =
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]]
sdag: Quantum object: dims=[[1, 1], [7, 7]], shape=(1, 49), type='bra', dtype=Dense
Qobj data =
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]]
sdag: Quantum object: dims=[[1, 1], [7, 7]], shape=(1, 49), type='bra', dtype=Dense
Qobj data =
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]]
sdag: Quantum object: dims=[[1, 1], [7, 7]], shape=(1, 49), type='bra', dtype=Dense
Qobj data =
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]]
sdag: Quantum object: dims=[[1, 1], [7, 7]], shape=(1, 49), type='bra', dtype=Dense
Qobj data =
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]]
sdag: Quantum object: dims=[[1, 1], [7, 7]], shape=(1, 49), type='bra', dtype=Dense
Qobj data =
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]]
sdag: Quantum object: dims=[[1, 1], [7, 7]], shape=(1, 49), type='bra', dtype=Dense
Qobj data =
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]]
sdag: Quantum object: dims=[[1, 1], [7, 7]], shape=(1, 49), type='bra', dtype=Dense
Qobj data =
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]]
sdag: Quantum object: dims=[[1, 1], [7, 7]], shape=(1, 49), type='bra', dtype=Dense
Qobj data =
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]]
sdag: Quantum object: dims=[[1, 1], [7, 7]], shape=(1, 49), type='bra', dtype=Dense
Qobj data =
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]]
sdag: Quantum object: dims=[[1, 1], [7, 7]], shape=(1, 49), type='bra', dtype=Dense
Qobj data =
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]]
sdag: Quantum object: dims=[[1, 1], [7, 7]], shape=(1, 49), type='bra', dtype=Dense
Qobj data =
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]]
sdag: Quantum object: dims=[[1, 1], [7, 7]], shape=(1, 49), type='bra', dtype=Dense
Qobj data =
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]]
sdag: Quantum object: dims=[[1, 1], [7, 7]], shape=(1, 49), type='bra', dtype=Dense
Qobj data =
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]]
sdag: Quantum object: dims=[[1, 1], [7, 7]], shape=(1, 49), type='bra', dtype=Dense
Qobj data =
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]]
sdag: Quantum object: dims=[[1, 1], [7, 7]], shape=(1, 49), type='bra', dtype=Dense
Qobj data =
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]]
sdag: Quantum object: dims=[[1, 1], [7, 7]], shape=(1, 49), type='bra', dtype=Dense
Qobj data =
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]]
sdag: Quantum object: dims=[[1, 1], [7, 7]], shape=(1, 49), type='bra', dtype=Dense
Qobj data =
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]]
sdag: Quantum object: dims=[[1, 1], [7, 7]], shape=(1, 49), type='bra', dtype=Dense
Qobj data =
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]]
sdag: Quantum object: dims=[[1, 1], [7, 7]], shape=(1, 49), type='bra', dtype=Dense
Qobj data =

#### Mode frequencies (MHz)

###### Numerical diagonalization

Lj        10
0    6804.51
1   20417.31

#### Kerr Non-linear coefficient table (MHz)

###### Numerical diagonalization

             0         1
Lj
10 0  1.45e-07  6.75e-08
   1  6.75e-08  7.86e-09

In [ ]:
eig_qb.sim.close()

Warning! 3 COM references still alive
Ansys will likely refuse to shut down